apiVersion: apps/v1
kind: Deployment
metadata:
  name: eatsdeployment
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: eats
  template:
    metadata:
      labels:
        app: eats
    spec:
      containers:
      - name: eats
        image: ignacioborraz/eats:1.0.0
        ports:
        - containerPort: 9099
        imagePullPolicy: IfNotPresent